
CREATE DATABASE IF NOT EXISTS `ancssc` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
USE `ancssc`;




-- DROP TABLE IF EXISTS `Organisation`;
-- DROP TABLE IF EXISTS `Participating_Organisation`;
-- DROP TABLE IF EXISTS `Basic_Project_Info`;
-- DROP TABLE IF EXISTS `Contact_Info`;
-- DROP TABLE IF EXISTS `Country`;
-- DROP TABLE IF EXISTS `Coordinates`;
-- DROP TABLE IF EXISTS `Geo_Info`;
-- DROP TABLE IF EXISTS `Tags`;
-- DROP TABLE IF EXISTS `Classifications`;
-- DROP TABLE IF EXISTS `Currency`;
-- DROP TABLE IF EXISTS `Budget`;
-- DROP TABLE IF EXISTS `Project_Impact`;
-- DROP TABLE IF EXISTS `Challanges_And_Solutions`;


CREATE TABLE IF NOT EXISTS `Organisation` (
  `ANCSSC_ID` int NOT NULL,
  `IATI_ID` varchar(255) DEFAULT NULL,
  `REPORTING_ORG` varchar(255) DEFAULT NULL,
  `ORG_TYPE` int NOT NULL,
  PRIMARY KEY (ANCSSC_ID)
);




CREATE TABLE IF NOT EXISTS `Participating_Organisation` (
	`ID` int NOT NULL,
	`ANCSSC_ID` int NOT NULL,
	`NAME` varchar(255) DEFAULT NULL,
	`ORG_TYPE` int NOT NULL,
	`ROLE` int NOT NULL,

	PRIMARY KEY (ID),
	FOREIGN KEY (ANCSSC_ID) REFERENCES Organisation(ANCSSC_ID)
);

CREATE TABLE IF NOT EXISTS `Basic_Project_Info` (
	`ID` int NOT NULL,
	`ANCSSC_ID` int NOT NULL,
	`TITLE` varchar(255) NOT NULL,
	`DESCRIPTION` varchar(255) DEFAULT NULL,
	`STATUS` int NOT NULL,
	`START_DATE` date NOT NULL,
	`END_DATE` date NOT NULL,
	`SCOPE` int NOT NULL,

	PRIMARY KEY (ID),
	FOREIGN KEY (ANCSSC_ID) REFERENCES Organisation(ANCSSC_ID)
);

CREATE TABLE IF NOT EXISTS `Contact_Info` (
	`ID` int NOT NULL,
	`PROJECT_ID` int NOT NULL,
	`NAME` varchar(255) NOT NULL,
	`DEPARTMENT` varchar(255) DEFAULT NULL,
	`PERSON_NAME` varchar(255) NOT NULL,
	`JOB_TITLE` varchar(255) NOT NULL,
	`TEL` varchar(255) DEFAULT NULL,
	`EMAIL` varchar(255) NOT NULL,
	`WEBSITE` varchar(255) DEFAULT NULL,
	`MAILING_ADDRESS` varchar(255) NOT NULL,
	

	PRIMARY KEY (ID),
	FOREIGN KEY (PROJECT_ID) REFERENCES  Basic_Project_Info(ID)
);

CREATE TABLE IF NOT EXISTS `Country` (
	`ID` int NOT NULL,
	`COUNTRY` varchar(255) NOT NULL,

	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS `Coordinates` (
	`ID` int NOT NULL,
	`LAT` int NOT NULL,
	`LONG` int NOT NULL,

	PRIMARY KEY (ID)
);


CREATE TABLE IF NOT EXISTS `Geo_Info` (
	`ID` int NOT NULL,
	`PROJECT_ID` int NOT NULL,
	`COUNTRY_ID` int NOT NULL,
	`RECIPIENT_REGION` int NOT NULL,
	`COORDINATES_ID` int NOT NULL,

	PRIMARY KEY (ID),
	FOREIGN KEY (PROJECT_ID) REFERENCES  Basic_Project_Info(ID),
	FOREIGN KEY (COUNTRY_ID) REFERENCES Country(ID),
	FOREIGN KEY (COORDINATES_ID) REFERENCES Coordinates(ID)

);

DROP TABLE IF EXISTS `Classifications`;
CREATE TABLE IF NOT EXISTS `Classifications` (
	`ID` int NOT NULL,
	`PROJECT_ID` int NOT NULL,
	`SECTOR` int NOT NULL,
	

	PRIMARY KEY (ID),
	FOREIGN KEY (PROJECT_ID) REFERENCES  Basic_Project_Info(ID)
);


CREATE TABLE IF NOT EXISTS `Tags` (
	`ID` int NOT NULL,
	`CLASSIFICATIONS_ID` int NOT NULL,
	`TAG` int NOT NULL,

	PRIMARY KEY (ID),
	FOREIGN KEY (CLASSIFICATIONS_ID) REFERENCES Classifications(ID)
);





CREATE TABLE IF NOT EXISTS `Currency` (
	`ID` int NOT NULL,
	`Currency` varchar(5) NOT NULL,

	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS `Budget` (
	`ID` int NOT NULL,
	`PROJECT_ID` int NOT NULL,
	`TYPE` int DEFAULT NULL,
	`STATUS` int DEFAULT NULL,
	`PERIOD_START` date DEFAULT NULL,
	`PERIOD_END` date DEFAULT NULL,
	`VALUE` varchar(255) DEFAULT NULL,
	`CURRENCY_ID` int DEFAULT NULL,
	`VALUE_DATE` date DEFAULT NULL,

	PRIMARY KEY (ID),
	FOREIGN KEY (PROJECT_ID) REFERENCES  Basic_Project_Info(ID),
	FOREIGN KEY (CURRENCY_ID) REFERENCES Currency(ID)

);



CREATE TABLE IF NOT EXISTS `Project_Impact` (
	`ID` int NOT NULL,
	`PROJECT_ID` int NOT NULL,
	`PROJECT_REACH_UNIT` varchar(255) DEFAULT NULL,
	`PROJECT_REACH_TARGET` varchar(255) DEFAULT NULL,
	`PROJECT_REACH_ACTUAL` varchar(255) DEFAULT NULL,
	`TARGET_GROUPS` varchar(255) DEFAULT NULL,

	PRIMARY KEY (ID),
	FOREIGN KEY (PROJECT_ID) REFERENCES  Basic_Project_Info(ID)


);

CREATE TABLE IF NOT EXISTS `Challanges_And_Solutions` (
	`ID` int NOT NULL,
	`PROJECT_ID` int NOT NULL,
	`CHALLANGE_TITLE` varchar(255) NOT NULL,
	`CHALLENGE_STATUS` int NOT NULL,
	`CHALLENGE_TYPE` int NOT NULL,
	`CHALENGE_DESCRIPTION` varchar(255) NOT NULL,
	`SOLUTION_TYPE` int DEFAULT NULL,
	`SOLUTION_DESCRIPTION` varchar(255) DEFAULT NULL,
	`CAN_BE_CONTRACTED` boolean DEFAULT NULL,

	PRIMARY KEY (ID),
	FOREIGN KEY (PROJECT_ID) REFERENCES  Basic_Project_Info(ID)

);





















