"""This document enforces as standard the ordering of the files when running through them, prevending any possible confusion of information"""
fileList = ['reports/Prakriye – Annual Report.pdf', 'reports/PLANACT-AR-17_18-002...pdf', 'reports/tanzania-2018.pdf',
            'reports/2019_39593758-3.pdf', 'reports/2018ImpactReport-AsanteAfrica-small.pdf',
            'reports/Annual Report 2017-18.pdf', 'reports/the-arcenciel-impact-report-2018-final.pdf',
            'reports/GOJoven-results-eval-2012.pdf', 'reports/Annual_Report_2017-2018.pdf',
            'reports/EDUCO-Accountability-Report-2018.pdf', 'reports/Badabon-Sangho-Annual-Report-2017-2018_PDF.pdf',
            'reports/attachment-19c116ec6cc5b6f71c4c0c036e8b8edf.pdf', 'reports/2018-WISER-Annual-Report.pdf',
            'reports/BLS19063_PRO_SOWF_REPORT_015.pdf', 'reports/IHAP2018.pdf',
            'reports/RECO Annual Report 2016-2018.pdf', 'reports/SDG_Impact_Report_190906.pdf',
            'reports/2018-Annual-Report_web.pdf', 'reports/Annual_Report__w_2018.pdf',
            'reports/1538109773-TahaddiStrategicPlan2018-2021Compressed.pdf',
            'reports/2018-GFP-Annual-Report-Design.pdf', 'reports/BOMA-Q1-2019-FINAL-2.pdf', 'reports/Winter-2018.pdf',
            'reports/Project+Soar+AR+2018+FINAL.pdf', 'reports/Annual_Report_2017-18.pdf',
            'reports/GOJoven-Impact-Sheet-3-2016.pdf', 'reports/CIUK-Annual-Report-and-Accounts-2018.pdf',
            'reports/PCI_MNCH_Nutrition_Capacity_Statement.pdf', 'reports/FXB-2017-Annual-Report.pdf',
            'reports/PCI_Every_Preemie_Program_Overview.pdf', 'reports/Annual_report_2017.pdf',
            'reports/966772306264698623132095.pdf', 'reports/AR-2018-19.pdf',
            'reports/Bangladesh-Annual-Report-2018.pdf', 'reports/actionaid_uk_annual_report_2018.pdf',
            'reports/A201+UP+annual+report+and+financial+statements+2018+final.pdf',
            'reports/Aura Freedom International Our Impact CanadaHelps.pdf', 'reports/Both_ENDS_Annual_Report_2018.pdf',
            'reports/GDS-Annual-Report-2017-18-final-1.pdf', 'reports/READ_annual_report_2018_Final_Compressed.pdf',
            'reports/arsberattelse-2018_inlaga_uppslag_eng_12juli.pdf', 'reports/REPORTE-ANUAL-2018.pdf',
            'reports/PCI_Food_for_Education_Programs_Overview.pdf', 'reports/Self-Help-Intl-2018-Impact-Report.pdf',
            'reports/PEACE_Final_Summary.pdf', 'reports/GNRC-Annual-Report-16-17-Singles-25-04-17.pdf',
            'reports/PHASEWORLDWIDE_IMPACTREPORT_2018.pdf', 'reports/Heifer-Annual-Report-2018.pdf',
            'reports/Friends-International-Annual-Report-2017.pdf', 'reports/access_to_justice_2018_final_report.pdf',
            'reports/iDE-2018-Annual-Report-web.pdf', 'reports/Summary-FXBVillage-Villupuram-Evaluation-2017.pdf',
            'reports/informe de gestion 2018.pdf', 'reports/cw_AnnualReport_2018_2.pdf',
            'reports/REO-2017-Annual-Report-1.pdf', 'reports/1534278448-FinalAnnualreportTahaddi8-8-2018(1).pdf',
            'reports/PCI_Annual_Report_2018_web.pdf', 'reports/SOUL+FY17-18+Annual+Report.pdf',
            'reports/084-201916irc_annualdef_web_0.pdf', 'reports/EG_RCT Interim Results.pdf',
            'reports/Winter-2017.pdf', 'reports/HFHI_AR_2018_FINAL_WEB2.pdf', 'reports/Aflatoun_AnnualReport2017.pdf',
            'reports/Annual Report 2017-18 Master.pdf', 'reports/PM-Manhood-2-0-Program-Overview-v1-7-E.pdf',
            'reports/GV_Annual-Report_final_web-1.pdf', 'reports/Annual_Report_2018.pdf',
            'reports/global-childhood-report-2019-pdf.pdf', 'reports/planinternational-annualreview2018-en.pdf',
            'reports/monitoring_report_2018_2.pdf', 'reports/BOMA-PROJECT-2018-Q4-IMPACT-REPORT-UPLOAD.pdf',
            'reports/PCI_Citizen_Security_Project_Overview_Nicaragua_Eng.pdf', 'reports/Aahung-Annual-Report-2018.pdf',
            'reports/MIET_AnnualReport_aw.pdf', 'reports/Annual-Report-2018-19-2.pdf',
            'reports/Annual-report-cob-2018.pdf', 'reports/camfed_intl_annual_report_2018.pdf',
            'reports/ar-complete-draft1-14062019-with-old-cover-update25062019.pdf',
            'reports/PCI_Healthy_Start_Program_Overview.pdf', 'reports/CARE INT Digital Annual Report V7.pdf',
            'reports/cob-annual-report-2017.pdf', 'reports/Ikamva_Annual_final_web_LR.pdf',
            'reports/2018 Impact Report-2.pdf', 'reports/Pangolim-39.pdf',
            'reports/portrait-stc-annual-report-2018.pdf', 'reports/ENTREPRENEURS-DU-MONDE_Annual-report-2018.pdf',
            'reports/ar2018_english.pdf', 'reports/271083-FB-Annual-Report-PROOF3.pdf',
            'reports/annualreview-financialstatement-2018.pdf', 'reports/7.-GDS-Annual-Report-2018-19.pdf',
            'reports/2018-Annual-Report.pdf', 'reports/NYF-Annual-Report-2017-2018.pdf',
            'reports/scus-2019-21-plan-booklet.pdf', 'reports/yo_quiero_yo_puedo._reporte_anual_2018.pdf',
            'reports/9780429502538_googlepreview.pdf', 'reports/2018 Impact Report.pdf']


def getFileList():
    return fileList


