CREATE TABLE `cash_at_bank` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NGO_ID` int(11) NOT NULL,
  `AMOUNT` varchar(255) DEFAULT NULL,
  `YEAR` date DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `NGO_ID` (`NGO_ID`),
  CONSTRAINT `cash_at_bank_ibfk_1` FOREIGN KEY (`NGO_ID`) REFERENCES `ngo_data` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `classifications` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PROJECT_ID` int(11) NOT NULL,
  `SECTOR` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `PROJECT_ID` (`PROJECT_ID`),
  CONSTRAINT `classifications_ibfk_1` FOREIGN KEY (`PROJECT_ID`) REFERENCES `projects` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=240 DEFAULT CHARSET=utf8;

CREATE TABLE `expenses` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NGO_ID` int(11) NOT NULL,
  `PROGRAM_COSTS` int(11) DEFAULT NULL,
  `ADMIN_COSTS` int(11) DEFAULT NULL,
  `YEAR` date DEFAULT NULL,
  `PERCENTAGE_OF_TOTAL` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `NGO_ID` (`NGO_ID`),
  CONSTRAINT `expenses_ibfk_1` FOREIGN KEY (`NGO_ID`) REFERENCES `ngo_data` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `income` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NGO_ID` int(11) NOT NULL,
  `GRANT_OR_DONATION` int(11) DEFAULT NULL,
  `LOAN` int(11) DEFAULT NULL,
  `NGO_CONTRIBUTION` int(11) DEFAULT NULL,
  `OTHER` int(11) DEFAULT NULL,
  `YEAR` date DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `NGO_ID` (`NGO_ID`),
  CONSTRAINT `income_ibfk_1` FOREIGN KEY (`NGO_ID`) REFERENCES `ngo_data` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ngo` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=74 DEFAULT CHARSET=utf8;

CREATE TABLE `ngo_data` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `REPORTING_ORG` varchar(255) DEFAULT NULL,
  `NGO_SINCE` varchar(255) DEFAULT NULL,
  `NGO_REGION` varchar(255) DEFAULT NULL,
  `NGO_STREET_ADDRESS` varchar(255) DEFAULT NULL,
  `NGO_POST_OR_ZIP` varchar(255) DEFAULT NULL,
  `NGO_CONTACT_NAME` varchar(255) DEFAULT NULL,
  `NGO_PHONE` varchar(255) DEFAULT NULL,
  `FOCUS_AREA` varchar(255) DEFAULT NULL,
  `MISSION` varchar(500) DEFAULT NULL,
  `NGO_ID` int(11) DEFAULT NULL,
  `PDF_NAME` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `NGO_ID` (`NGO_ID`),
  CONSTRAINT `ngo_data_ibfk_1` FOREIGN KEY (`NGO_ID`) REFERENCES `ngo` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=137 DEFAULT CHARSET=utf8;

CREATE TABLE `ngo_staff` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NGO_ID` int(11) NOT NULL,
  `PERSON_NAME` varchar(255) DEFAULT NULL,
  `JOB_TITLE` varchar(255) DEFAULT NULL,
  `DEPARTMENT` varchar(255) DEFAULT NULL,
  `TEL` varchar(255) DEFAULT NULL,
  `EMAIL` varchar(255) DEFAULT NULL,
  `MAILING_ADDRESS` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `NGO_ID` (`NGO_ID`),
  CONSTRAINT `ngo_staff_ibfk_1` FOREIGN KEY (`NGO_ID`) REFERENCES `ngo_data` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=122 DEFAULT CHARSET=utf8;

CREATE TABLE `pdfs` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PDF_NAME` varchar(100) DEFAULT NULL,
  `NGO_NAME` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=100 DEFAULT CHARSET=utf8;

CREATE TABLE `program_cost_breakdown` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NGO_ID` int(11) NOT NULL,
  `AGRICULTURE_COST` int(11) DEFAULT NULL,
  `EMPOWERMNENT_ADOLESCENTS_COST` int(11) DEFAULT NULL,
  `EDUCATION_COST` int(11) DEFAULT NULL,
  `TRAINING_COST` int(11) DEFAULT NULL,
  `OTHER_COST` int(11) DEFAULT NULL,
  `YEAR` date DEFAULT NULL,
  `PERCENTAGE_OF_TOTAL` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `NGO_ID` (`NGO_ID`),
  CONSTRAINT `program_cost_breakdown_ibfk_1` FOREIGN KEY (`NGO_ID`) REFERENCES `ngo_data` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `project_finance` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PROJECT_ID` int(11) NOT NULL,
  `PERIOD_START` varchar(255) DEFAULT NULL,
  `PERIOD_END` varchar(255) DEFAULT NULL,
  `AMOUNT` varchar(255) DEFAULT NULL,
  `CURRENCY` varchar(255) DEFAULT NULL,
  `VALUE_DATE` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `PROJECT_ID` (`PROJECT_ID`),
  CONSTRAINT `project_finance_ibfk_1` FOREIGN KEY (`PROJECT_ID`) REFERENCES `projects` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=222 DEFAULT CHARSET=utf8;

CREATE TABLE `project_geo_info` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PROJECT_ID` int(11) NOT NULL,
  `PROJECT_COUNTRY` varchar(200) DEFAULT NULL,
  `PROJECT_REGION` varchar(255) DEFAULT NULL,
  `PROJECT_ADDRESS` varchar(255) DEFAULT NULL,
  `PROJECT_POST_OR_ZIP` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `PROJECT_ID` (`PROJECT_ID`),
  CONSTRAINT `project_geo_info_ibfk_1` FOREIGN KEY (`PROJECT_ID`) REFERENCES `projects` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=246 DEFAULT CHARSET=utf8;

CREATE TABLE `project_impact` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PROJECT_ID` int(11) NOT NULL,
  `PROJECT_REACH_UNIT` varchar(255) DEFAULT NULL,
  `PROJECT_REACH_TARGET` varchar(255) DEFAULT NULL,
  `PROJECT_REACH_ACTUAL` varchar(255) DEFAULT NULL,
  `PROJECT_TARGET_GROUPS` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `PROJECT_ID` (`PROJECT_ID`),
  CONSTRAINT `project_impact_ibfk_1` FOREIGN KEY (`PROJECT_ID`) REFERENCES `projects` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=239 DEFAULT CHARSET=utf8;

CREATE TABLE `project_statistics` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NGO_ID` int(11) NOT NULL,
  `NGO_COMPLETED_PROJECTS` int(11) DEFAULT NULL,
  `NGO_TOTAL_PROJECTS` int(11) DEFAULT NULL,
  `PERCENTAGE_OF_TOTAL` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `NGO_ID` (`NGO_ID`),
  CONSTRAINT `project_statistics_ibfk_1` FOREIGN KEY (`NGO_ID`) REFERENCES `ngo_data` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `projects` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NGO_ID` int(11) NOT NULL,
  `PROJECT_TITLE` varchar(255) DEFAULT NULL,
  `PROJECT_DESCRIPTION` varchar(255) DEFAULT NULL,
  `PROJECT_STATUS` varchar(255) DEFAULT NULL,
  `PROJECT_START_DATE` varchar(255) DEFAULT NULL,
  `PROJECT_END_DATE` varchar(255) DEFAULT NULL,
  `PROJECT_SCOPE` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `NGO_ID` (`NGO_ID`),
  CONSTRAINT `projects_ibfk_1` FOREIGN KEY (`NGO_ID`) REFERENCES `ngo_data` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=282 DEFAULT CHARSET=utf8;

CREATE TABLE `sponsors` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NGO_ID` int(11) NOT NULL,
  `NGO_NAME` varchar(255) DEFAULT NULL,
  `SPONSOR_NAME` varchar(255) DEFAULT NULL,
  `SPONSOR_TYPE` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `NGO_ID` (`NGO_ID`),
  CONSTRAINT `sponsors_ibfk_1` FOREIGN KEY (`NGO_ID`) REFERENCES `ngo_data` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=123 DEFAULT CHARSET=utf8;

CREATE TABLE `statistics` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NGO_ID` int(11) NOT NULL,
  `AVG_PROJECT_BUDGET` varchar(40) DEFAULT NULL,
  `AVERAGE_COMPLETION_TIME` varchar(40) DEFAULT NULL,
  `PER_REGION` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `NGO_ID` (`NGO_ID`),
  CONSTRAINT `statistics_ibfk_1` FOREIGN KEY (`NGO_ID`) REFERENCES `ngo_data` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `taxes_or_insurance` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NGO_ID` int(11) NOT NULL,
  `STAFF_TAX` int(11) DEFAULT NULL,
  `SOCIAL_INSURANCE` int(11) DEFAULT NULL,
  `YEAR` date DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `NGO_ID` (`NGO_ID`),
  CONSTRAINT `taxes_or_insurance_ibfk_1` FOREIGN KEY (`NGO_ID`) REFERENCES `ngo_data` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

