use `team_36_db_do_not_touch`;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS NGO;
DROP TABLE IF EXISTS Statistics;
DROP TABLE IF EXISTS Sponsors;
DROP TABLE IF EXISTS Projects;
DROP TABLE IF EXISTS Contact_Info;
DROP TABLE IF EXISTS Coordinates;
DROP TABLE IF EXISTS Project_Geo_Info;
DROP TABLE IF EXISTS Classifications;
DROP TABLE IF EXISTS Project_Finance;
DROP TABLE IF EXISTS Project_Impact;
DROP TABLE IF EXISTS Project_Statistics;
DROP TABLE IF EXISTS NGO_geo_info;
DROP TABLE IF EXISTS Classifications; 

SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE IF NOT EXISTS NGO (
   ID int NOT NULL,
   REPORTING_ORG varchar(255) DEFAULT NULL,
   NGO_NAME varchar(40) DEFAULT NULL,

   NGO_SINCE varchar(45) DEFAULT NULL,

   NGO_CONTACT_NAME varchar(255) DEFAULT NULL,
   NGO_PHONE varchar(20) DEFAULT NULL,

   FOCUS_AREA varchar(45) DEFAULT NULL,
   MISSION varchar(500) DEFAULT null,

   PRIMARY KEY (NGO_ID)
);

CREATE TABLE IF NOT EXISTS NGO_geo_info(
	ID int not NULL,
	NGO_ID int not NULL, 
	NGO_REGION varchar(45) DEFAULT NULL,
    NGO_STREET_ADDRESS varchar(40) DEFAULT NULL,
    NGO_POST_OR_ZIP varchar(40) DEFAULT NULL,

	PRIMARY KEY(ID),
	FOREIGN KEY(NGO_ID) REFERENCES NGO(NGO_ID)
);

CREATE TABLE IF NOT EXISTS Project_Statistics(
    ID int not NULL,
    NGO_ID int not NULL,
    NGO_COMPLETED_PROJECTS INT DEFAULT NULL,
    NGO_TOTAL_PROJECTS INT DEFAULT NULL,
    PERCENTAGE_OF_TOTAL int DEFAULT NULL,

	PRIMARY KEY(ID),
    FOREIGN KEY(NGO_ID) REFERENCES NGO(NGO_ID)
);

CREATE TABLE IF NOT EXISTS Statistics(
	ID int NOT NULL,
	NGO_ID int NOT NULL,
	AVG_PROJECT_BUDGET varchar(40) DEFAULT NULL,
	AVERAGE_COMPLETION_TIME varchar(40) DEFAULT NULL,
	PER_REGION int DEFAULT NULL,
    
	PRIMARY KEY (ID),
	FOREIGN KEY (NGO_ID) REFERENCES NGO(NGO_ID)
);

CREATE TABLE IF NOT EXISTS Sponsors(
	ID int NOT NULL,
	NGO_ID int NOT NULL,
    NGO_NAME int DEFAULT NULL,
	SPONSOR_NAME varchar(255) DEFAULT NULL,
	SPONSOR_TYPE int DEFAULT NULL,   

	PRIMARY KEY (ID),
	FOREIGN KEY (NGO_ID) REFERENCES NGO(NGO_ID)
);

CREATE TABLE IF NOT EXISTS Projects(
	ID int NOT NULL,
	NGO_ID int NOT NULL,
	PROJECT_TITLE varchar(255) DEFAULT NULL,
	PROJECT_DESCRIPTION varchar(255) DEFAULT NULL,
	PROJECT_STATUS int DEFAULT NULL,
	PROJECT_START_DATE date DEFAULT NULL,
	PROJECT_END_DATE date DEFAULT NULL,
	PROJECT_SCOPE int DEFAULT NULL,

	PRIMARY KEY (ID),
	FOREIGN KEY (NGO_ID) REFERENCES NGO(NGO_ID)
);

CREATE TABLE IF NOT EXISTS NGO_Staff(
	ID int NOT NULL,
	NGO_ID int NOT NULL,
    PERSON_NAME int DEFAULT NULL,
    JOB_TITLE varchar(255) DEFAULT NULL,
	DEPARTMENT varchar(255) DEFAULT NULL,
	TEL varchar(255) DEFAULT NULL,
	EMAIL varchar(255) DEFAULT NULL,
	MAILING_ADDRESS varchar(255) DEFAULT NULL,
	
	PRIMARY KEY (ID),
	FOREIGN KEY (NGO_ID) REFERENCES NGO(NGO_ID)
);


CREATE TABLE IF NOT EXISTS Project_Geo_Info(
	ID int NOT NULL,
	PROJECT_ID int NOT NULL,
	PROJECT_COUNTRY varchar(40) DEFAULT NULL,
	PROJECT_REGION int DEFAULT NULL,
	PROJECT_ADDRESS varchar(255) DEFAULT NULL, 
    PROJECT_POST_OR_ZIP varchar(40) DEFAULT NULL,

	PRIMARY KEY (ID),
	FOREIGN KEY (PROJECT_ID) REFERENCES Projects(ID)
);

CREATE TABLE IF NOT EXISTS Classifications(
	ID int NOT NULL,
	PROJECT_ID int NOT NULL,
	SECTOR int DEFAULT NULL,

	PRIMARY KEY (ID),
	FOREIGN KEY (PROJECT_ID) REFERENCES Projects(ID)
);

CREATE TABLE IF NOT EXISTS Project_Finance(
	ID int NOT NULL,
	PROJECT_ID int NOT NULL,
	PERIOD_START date DEFAULT NULL,
	PERIOD_END date DEFAULT NULL,
	AMOUNT varchar(255) DEFAULT NULL,
	CURRENCY varchar(40) DEFAULT NULL,
	VALUE_DATE date DEFAULT NULL,

	PRIMARY KEY (ID),
	FOREIGN KEY (PROJECT_ID) REFERENCES Projects(ID)
);


CREATE TABLE IF NOT EXISTS Project_Impact (
	ID int NOT NULL,
	PROJECT_ID int NOT NULL,
	PROJECT_REACH_UNIT varchar(255) DEFAULT NULL,
	PROJECT_REACH_TARGET varchar(255) DEFAULT NULL,
	PROJECT_REACH_ACTUAL varchar(255) DEFAULT NULL,
	PROJECT_TARGET_GROUPS varchar(255) DEFAULT NULL,

	PRIMARY KEY (ID),
	FOREIGN KEY (PROJECT_ID) REFERENCES Projects(ID)
);

CREATE TABLE IF NOT EXISTS Program_Cost_Breakdown(
    ID int NOT NULL, 
    NGO_ID int NOT NULL,
    AGRICULTURE_COST int DEFAULT NULL, 
    EMPOWERMNENT_ADOLESCENTS_COST int DEFAULT NULL, 
    EDUCATION_COST int DEFAULT NULL, 
    TRAINING_COST int DEFAULT NULL, 
    OTHER_COST int DEFAULT NULL, 
    YEAR date DEFAULT NULL, 
    PERCENTAGE_OF_TOTAL int DEFAULT NULL, 

    PRIMARY KEY(ID),
    FOREIGN KEY(NGO_ID) REFERENCES NGO(NGO_ID)
);

CREATE TABLE IF NOT EXISTS Taxes_Or_Insurance(
    ID int NOT NULL, 
    NGO_ID int NOT NULL, 
    STAFF_TAX int DEFAULT NULL, 
    SOCIAL_INSURANCE int DEFAULT NULL, 
    YEAR date DEFAULT NULL, 

    PRIMARY KEY(ID),
    FOREIGN KEY(NGO_ID) REFERENCES NGO(NGO_ID)
);

CREATE TABLE IF NOT EXISTS Income(
    ID int NOT NULL, 
    NGO_ID int NOT NULL, 
    GRANT_OR_DONATION int DEFAULT NULL, 
    LOAN int DEFAULT NULL, 
    NGO_CONTRIBUTION int DEFAULT NULL, 
    OTHER int DEFAULT NULL, 
    YEAR date DEFAULT NULL, 

    PRIMARY KEY(ID),
    foreign KEY(NGO_ID) REFERENCES NGO(NGO_ID) 
);

CREATE TABLE IF NOT EXISTS Cash_At_Bank(
    ID int NOT NULL, 
    NGO_ID int not null,
    AMOUNT int DEFAULT NULL, 
    YEAR date DEFAULT NULL, 

    PRIMARY KEY(ID), 
    FOREIGN KEY(NGO_ID) REFERENCES NGO(NGO_ID)
);

CREATE TABLE IF NOT EXISTS Expenses(
    ID int NOT NULL, 
    NGO_ID int not null,
    PROGRAM_COSTS int DEFAULT NULL, 
    ADMIN_COSTS int DEFAULT NULL, 
    YEAR date DEFAULT NULL, 
    PERCENTAGE_OF_TOTAL int DEFAULT NULL,

    PRIMARY KEY(ID), 
    foreign KEY(NGO_ID) REFERENCES NGO(NGO_ID)
);




