CREATE TABLE IF NOT EXISTS `PDFs` (
	`ID` int NOT NULL AUTO_INCREMENT,
	`PDF_NAME` varchar(45) DEFAULT NULL,
	`NGO_NAME` varchar(45) DEFAULT NULL,
	`NGO_ID` int DEFAULT NULL,

  	PRIMARY KEY (ID),
  	FOREIGN KEY (NGO_ID) REFERENCES ngo(NGO_ID)
);